service: front-rec-ai
runtime: python37

automatic_scaling:
  min_instances: 3

handlers:
- url: /
  static_files: dist/retail/index.html
  upload: dist/retail/index.html
- url: /
  static_dir: dist/retail