service: front-rec-ai
runtime: python37

automatic_scaling:
  min_instances: 3

handlers:
- url: /(.*\.(js|css|svg|png)(|\.map))$
  static_files: dist/retail/\1
  upload: dist/retail/(.*)(|\.map)
- url: /.*
  static_files: dist/retail/index.html
  upload: dist/retail/.*