GET_BRAND_QUERY = "select distinct brand from products"

GET_PRODUCT_QUERY = """SELECT A.ID, A.RETAIL_PRICE as PRICE, NAME ,SIZE ,COLOR, BRAND as COMPANY, CATEGORY, SUB_CATEGORY,image_link ,REVIEW ,AVAILABILITY ,DATE_ADD(CURRENT_DATE(), INTERVAL 
CAST(ESTIMATED_DELIVERY_DAY AS SIGNED) DAY) AS ESTIMATE_DELIVERY_AT FROM `products` A LEFT JOIN `review` B ON A.ID = B.PRODUCT_ID WHERE A.ID = {} GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12 """

GET_CATAGORY_QUERY = "SELECT CATEGORY,GROUP_CONCAT(distinct SUB_CATEGORY ORDER BY SUB_CATEGORY ASC SEPARATOR ', " \
                     "') AS SUB_CATEGORY  FROM Retail.products GROUP BY 1 "

GET_SALES_QUERY = """SELECT PRODUCT_NAME, COUNT(CASE WHEN TRIM(LOWER(STATUS)) = 'cancelled' 
THEN 1 END) AS COUNT_CANCELLED, COUNT(CASE WHEN TRIM(LOWER(STATUS)) = 'processing' THEN 1 END) AS COUNT_PROCESSING, 
COUNT(CASE WHEN TRIM(LOWER(STATUS)) = 'complete' THEN 1 END) AS COUNT_COMPLETE, COUNT(CASE WHEN TRIM(LOWER(STATUS)) = 
'returned' THEN 1 END) AS COUNT_RETURNED, COUNT(CASE WHEN TRIM(LOWER(STATUS)) = 'shipped' THEN 1 END) AS 
COUNT_SHIPPED FROM order_items A LEFT JOIN inventory_items B ON A.INVENTORY_ITEM_ID = B.ID  GROUP BY 1 """


GET_FILTER_QUERY = """SELECT A.ID,A.RETAIL_PRICE as PRICE, BRAND, NAME ,SIZE ,COLOR, CATEGORY, SUB_CATEGORY, image_link ,REVIEW ,AVAILABILITY ,DATE_ADD(
CURRENT_DATE(), INTERVAL CAST(ESTIMATED_DELIVERY_DAY AS SIGNED) DAY) AS ESTIMATE_DELIVERY_AT FROM 
`products` A LEFT JOIN 
`review` B ON A.ID = B.PRODUCT_ID WHERE {} GROUP BY 1,2,3,4,5,6,7, 8, 9,10,11,12 """


GET_USER_EVENT = """SELECT USER_ID,CITY,STATE,COUNTRY,EVENT_TYPE,CREATED_AT AS DATE FROM 
`events` GROUP BY 1,2,3,4,5,6 """


GET_TOP_PRODUCT_QUERY = """SELECT A.ID, A.RETAIL_PRICE as PRICE, NAME ,SIZE ,COLOR, BRAND as COMPANY ,CATEGORY, SUB_CATEGORY, image_link ,REVIEW ,AVAILABILITY ,DATE_ADD(CURRENT_DATE(), INTERVAL 
CAST(ESTIMATED_DELIVERY_DAY AS SIGNED) DAY) AS ESTIMATE_DELIVERY_AT FROM 
`products` A LEFT JOIN 
`review` B ON A.ID = B.PRODUCT_ID WHERE A.ID IN {} GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12 """
