import os

is_prod = True if 'GAE_DEPLOYMENT_ID' in os.environ else False


ELASTICSEARCH_INDEX = 'products'
#TODO: move ES secrets to SecretManager
ELASTICSEARCH_CLOUD_ID = 'RetailStore:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDkwZmZhNWM2NjI0YjRhYTQ5YzNiZjRkOGZlNWVlMzFiJDU4Y2M0MmI2OTExYTRhOTY4NGJlM2FjZTgxOTk3M2Fk'
ELASTICSEARCH_USER = 'elastic'
ELASTICSEARCH_PASSWORD = 'lOhWUMPhC03lg1CfGtQsph6c'
