service: backend-q
#service: default
runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3
manual_scaling:
  instances: 1
vpc_access_connector:
  name: projects/babrams-recai-demo/locations/us-central1/connectors/recai-demo-serverless-vpc   #network name

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  RECAI_PROJECT: "babrams-recai-demo-test"
  PROJECT_NUMBER: "371922342503"
  PREDICT_KEY: "AIzaSyAptd6M3SUokdQKMgCAssv-adCOP7fO8s8"
  OAUTH_CLIENT: "371922342503-p4sjpo0kc7emoeesodou8kqsv8dnhem6.apps.googleusercontent.com"
  OAUTH_KEY: "lwfhDWxWrZ6SEAgtkwVpHrcs"
  CLOUD_SQL_IP: "10.108.0.3"
  HP_PLACEMENT: "homepage"
  OYML_PLACEMENT: "pdp"
  FBT_PLACEMENT: "copurchased"
