service: backend-q
#service: default
runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3
manual_scaling:
  instances: 1
vpc_access_connector:
  name: projects/${RECAI_PROJECT}/locations/us-central1/connectors/recai-demo-serverless-vpc   #network name

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
