GET_PRODUCT_QUERY_COLUMNS = [
    'ID',
    'PRICE',
    'NAME',
    'SIZE',
    'COLOR',
    'COMPANY',
    'CATEGORY',
    'SUB_CATEGORY',
    'IMAGE_LINK',
    'REVIEW',
    'AVAILABILITY',
    'ESTIMATE_DELIVERY_AT'
]

GET_BRAND_QUERY_COLUMNS = [
    'BRAND'
]

GET_CATAGORY_QUERY_COLUMNS = [
    'CATEGORY',
    'SUB_CATEGORY'
]

GET_FILTER_QUERY_COLUMNS = [
    'ID',
    'PRICE',
    'COMPANY',
    'NAME',
    'SIZE',
    'COLOR',
    'CATEGORY',
    'SUB_CATEGORY',
    'IMAGE LINK',
    'REVIEW',
    'AVAILABILITY',
    'ESTIMATE_DELIVERY_AT'
]

GET_SALES_QUERY_COLUMNS = [
    'PRODUCT_NAME',
    'COUNT_CANCELLED',
    'COUNT_PROCESSING',
    'COUNT_COMPLETE',
    'COUNT_RETURNED',
    'COUNT_SHIPPED'
]

GET_USER_DETAIL_COLUMNS = [
    'USER ID',
    'CITY',
    'STATE',
    'COUNTRY',
    'EVENT TYPE',
    'DATE'
]

GET_TOP_PRODUCT_QUERY = [
    'ID',
    'PRICE',
    'NAME',
    'SIZE',
    'COLOR',
    'COMPANY',
    'CATEGORY',
    'SUB_CATEGORY',
    'IMAGE_LINK',
    'REVIEW',
    'AVAILABILITY',
    'ESTIMATE_DELIVERY_AT'
]
